stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: '/certs'
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  IMAGE_TAG_LATEST: $CI_REGISTRY_IMAGE:latest

services:
  - docker:24.0.5-dind

before_script:
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

build:
  stage: build
  image: docker:24.0.5
  script:
    - echo "Building Docker image..."
    - docker build --pull -t $IMAGE_TAG -t $IMAGE_TAG_LATEST .
    - echo "Pushing Docker image to registry..."
    - docker push $IMAGE_TAG
    - docker push $IMAGE_TAG_LATEST
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master"
      exists:
        - Dockerfile
