version: '3.8'
name: powerpump-frontend

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: 1
    restart: unless-stopped
