version: '3.8'
name: powerpump-frontend

services:
  web:
    image: registry.gitlab.com/ndlabs-power-pump/power-pump-webapp:latest
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
